services:
  postgres:
    image: postgres:16
    container_name: lebnani-postgres
    environment:
      POSTGRES_DB: lebnani
      POSTGRES_USER: lebnani
      POSTGRES_PASSWORD: lebnani
    ports:
      - "5432:5432"
    volumes:
      - lebnani-postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lebnani-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lebnani
      SPRING_DATASOURCE_USERNAME: lebnani
      SPRING_DATASOURCE_PASSWORD: lebnani
      APP_JWT_SECRET: CHANGE_THIS_SECRET_CHANGE_THIS_SECRET_CHANGE_THIS_SECRET_123456
      APP_JWT_EXPIRATION_MINUTES: 60
    ports:
      - "8080:8080"

  web:
    build:
      context: ./frontend/lebnani-web
      dockerfile: Dockerfile
    container_name: lebnani-web
    depends_on:
      - api
    ports:
      - "4200:80"

volumes:
  lebnani-postgres-data: