sonar.projectKey=Henri-Fakhouri_lebnani
sonar.organization=henri-fakhouri

sonar.projectName=Lebnani
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main/java,frontend/lebnani-web/src
sonar.tests=backend/src/test/java,frontend/lebnani-web/src

sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/lebnani-web/coverage/lcov.info,frontend/lebnani-web/coverage/lebnani-web/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/target/**,**/*.spec.ts,backend/src/main/resources/db/migration/**
sonar.test.inclusions=backend/src/test/java/**/*.java,frontend/lebnani-web/src/**/*.spec.ts