sonar.projectKey=Henri-Fakhouri_lebnani
sonar.organization=henri-fakhouri

sonar.projectName=Lebnani
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main/java,frontend/lebnani-web/src
sonar.tests=backend/src/test/java

sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/target/**,**/*.spec.ts,backend/src/main/resources/db/migration/**
sonar.coverage.exclusions=frontend/lebnani-web/src/**,**/*Application.java,**/*Config.java,**/*Controller.java,**/*Request.java,**/*Response.java,**/*Repository.java,**/*Exception.java
sonar.test.exclusions=frontend/lebnani-web/src/**/*.spec.ts