sonar.projectKey=Henri-Fakhouri_lebnani
sonar.organization=henri-fakhouri

sonar.sources=backend/src/main/java,frontend/lebnani-web/src
sonar.tests=backend/src/test/java,frontend/lebnani-web/src
sonar.test.inclusions=backend/src/test/java/**/*.java,frontend/lebnani-web/src/**/*.spec.ts

sonar.java.binaries=backend/target/classes
sonar.java.libraries=backend/target/dependency/*.jar

sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/lebnani-web/coverage/lebnani-web/lcov.info

sonar.exclusions=backend/target/**,frontend/lebnani-web/node_modules/**,frontend/lebnani-web/coverage/**,frontend/lebnani-web/dist/**